#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap           0

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

#bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

# --------------- Feedback de preselección ----------------
bspc config presel_feedback      on
bspc config presel_feedback_color  "#56021F"
bspc config presel_border_color  "#ff0000"
bspc config presel_border_width  4
# ---------------------------------------------------------

# ---------------------- Fondo_barra -----------------------------
#usr/usr/bin/feh --bg-fill ~/desktop/fondos/fondo2.jpg & #un solo fondo

~/.config/bspwm/set-wallpaper.sh I &

bspc subscribe desktop_focus | while read -r _ _ desk_id; do
    desk_name=$(bspc query -D -d "$desk_id" --names)
    ~/.config/bspwm/set-wallpaper.sh "$desk_name"
done &

/home/lelowi/.config/polybar/launch.sh
# ----------------------------------------------------------------


# ------------------------- Otros --------------------------
wmname LG3G &
#picom --config ~/.config/picom/picom.conf &
~/.config/picom/launch.sh &
~/.config/eww/launcher.sh &
#eww daemon &
#eww open logo &
bspc config top_padding 45
# ----------------------------------------------------------



